
modLoader="javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId="additions"
version="1.0.1"
displayName="Additions"
authors="gobies"
description='''extra additions!'''

[[dependencies.additions]]
modId="forge"
mandatory= true
versionRange = "[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.additions]]
modId="minecraft"
mandatory= true
versionRange = "[1.20.1]"
ordering="NONE"
side="BOTH"

