
modLoader="javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId="additions"
version="1.0.5"
displayName="Additions"
authors="gobies"
description='''A collection of useful additions to Minecraft, including new blocks, items, and tools'''

[[dependencies.additions]]
modId="forge"
mandatory= true
versionRange = "[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.additions]]
modId="minecraft"
mandatory= true
versionRange = "[1.20.1]"
ordering="NONE"
side="BOTH"

